### ISSUE TITLE
add Mini-RF parameters

### ISSUE THREAD

**Issue by RayEspiritu** [pds-data-dictionaries/ldd-lro#13]
Additional Mini-RF parameters for monostatic and bistatic labels

**Comment by thareUSGS** [comment]
@RayEspiritu I'm planning to do a new release (v1.0.1.0) to this mission dictionary to allow for a 5th mission phase enumeration (to get us to 2025). And I also plane to update this to 1.I.0.0 information model (IM). 

Do you have any quick fixes for me? I have a short fuse for the pending LROC release. If you don't have the time right now for these updates, we can pull another release when you are ready.

**Comment by RayEspiritu** [comment]
I just merged my changes on the branch. It passed the validations, so hopefully this is ok?

I have additional keywords to add but I can do that after you make your release. Btw, when can we expect v1.0.1.0 ?

Thanks,
Ray


From: Trent Hare ***@***.***>
Reply-To: pds-data-dictionaries/ldd-lro ***@***.***>
Date: Monday, January 16, 2023 at 1:55 PM
To: pds-data-dictionaries/ldd-lro ***@***.***>
Cc: "Espiritu, Raymond C." ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [pds-data-dictionaries/ldd-lro] add Mini-RF parameters (Issue #13)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




@RayEspiritu<https://github.com/RayEspiritu> I'm planning to do a new release (v1.0.1.0) to this mission dictionary to allow for a 5th mission phase enumeration (to get us to 2025). And I also plane to update this to 1.I.0.0 information model (IM).

Do you have any quick fixes for me? I have a short fuse for the pending LROC release. If you don't have the time right now for these updates, we can pull another release when you are ready.

**Comment by thareUSGS** [comment]
@RayEspiritu So there are some attributes you have added that are already found within GEOM ([phase_angle](https://github.com/pds-data-dictionaries/ldd-geom/blob/9ad61348edda15777205e97081a569c86cffb247/src/PDS4_GEOM_IngestLDD.xml#L3518) and [emission_angle](https://github.com/pds-data-dictionaries/ldd-geom/blob/9ad61348edda15777205e97081a569c86cffb247/src/PDS4_GEOM_IngestLDD.xml#L3308)). 

I changed those to sar_phase_angle and sar_emission_angle to emulate the existing sar_incidence_angle already there. Are those really different than the normal definition (found in geom) or do you need them to be in the Mini-RF Class. If they are the same as in geom, can they be used from geom section in your labels (or do you prefer them to be in the mini-rf class?

**Comment by RayEspiritu** [comment]
sar_phase_angle really is different: it is the angle between the Mini-RF receiver and the Earth-based transmitter. It is also known as the bistatic angle. 

sar_incidence_angle is also different - it is the angle between the normal to the lunar DEM and the vector to the Earth-based transmitter. 

These came about because the Mini-RF transmitter failed during the normal science mission, so bistatic operations utilizes an Earth-based transmitter bouncing signals off the moon and into the Mini-RF receiver.

**Comment by thareUSGS** [comment]
Okay so it sounds like we are good with sar_phase_angle, sar_emission_angle, and the original sar_incidence_angle.  I used those explanations above for the two definitions too. Although, I don't have any definition yet for sar_emission_angle. There are a few other new attributes without definitions -- so those would be good additions at some point.

If you don't have anything else, I will get this merged into main and released soon (ETA within the week or so). LROC will likely change to this new LRO mission dictionary version also using the 1.I.0.0 (1.18.0.0) PDS information model.

**Comment by RayEspiritu** [comment]
i do not have anything else at this time. The Mini-RF team wants to do a redesign of the Bistatic archive in PDS4 and include additional datasets. As such, we are putting together a sample archive to include the redesigned data and new products so we can conduct a full PDS Peer Review. These will require more updates to the LDD, but I can wait until after you release the new version to add more keywords.
