### ISSUE TITLE
multiple mission phases

### ISSUE THREAD

**Issue by paulgeissler** [pds-data-dictionaries/ldd-lro#6]
Hello,

Some LROC RDR products use data from multiple mission phases ("NOMINAL MISSION", "SCIENCE MISSION", "EXTENDED SCIENCE MISSION")

The LRO mission dictionary currently allows only one mission phase.

Can I have permission to alter the ingest file to allow multiple mission phases? Where can I find the current version?

Thanks, Paul

**Comment by sslavney** [comment]
Paul,
The LRO dictionary is currently on the PDS Github at https://github.com/pds-data-dictionaries/ldd-lro.
It's fine with me to make mission phase multivalued. I don't know how the permission-giving process works on Github; do you submit your changes and the owner is then notified to approve or reject? I think Trent is the owner because he posted the dictionary for me. I'm ready to learn how to do this.
Susie

**Comment by thareUSGS** [comment]
I am happy to help push updates (but I consider you guys the the "owners". :-)

github can be awesome (but sometimes it makes me want to scream).  Maybe at the next "virtual" face-to-face we can do a little training session. Fortunately there are nice apps out there that generally make git and github easier.

-Trent
________________________________

**Comment by jordanpadams** [comment]
@thareUSGS @sslavney @paulgeissler EN is currently working on a process for approval and submission of LDD updates, as well as some automation for generating the dictionaries. however, the plan was for that to specifically revolve around discipline dictionaries, but it may be worth a discussion at the July F2F as to whether or not we should include mission dictionaries. 

that being said, a walkthrough of making a change specifically to an LDD in Github would probably be good. there are also a ton of resources online for training on the ins-and-outs of Github at your own pace: https://lab.github.com/

**Comment by sslavney** [comment]
Trent,
If you want to transfer ownership to me, that would be fine (is it possible?). I would really like to learn to manage a git repository myself. A training session would be helpful, as well as recommendations for apps. There's plenty of online help for git but it's overwhelming.

Meanwhile, Paul, suppose you just send me your updated LRO LDD files, I'll approve them, and then ask Trent to post.

Susie

**Comment by thareUSGS** [comment]
I have given you write access although at any time (even without write access), you (or anyone else) can request a "pull request" from your person "fork", and ask someone to review and accept the merge.

This is going to sound at first. But the goal for updating would be summarized as.
(1) "fork" this repository "ldd-lro" to your own github account. Use the fork button, top right of the page. You usually do this once.
(2) Now an exact copy exists on your own personal github account.
(3) From your own personal account, "clone" this to a local computer. You can use command git tools or a GUI application like GitHub Desktop or SourceTree. Now the files are local for editing.
(4) Once you are done updating the files, you can use git or the GUI applications (which will know which files have changed), select the files, add a comment for the updated files, and then "push". This will push the files from your local machine to your personal GitHub account. This is essentially a holding area to show the updates to others for comments (or testing). You should "push" changes often (small updates are recommended with their own comments). 
(5) Once you have all your new pushes to your personal GitHub (1 or more), you can now request a "pull request" from your personal account to the PDS ldd-lro account. This will you again to request a review prior to merging. Once you or another reviewer is happy, they can now "merge" in the changes (if no merge conflicts happen).

that is the simple life-cycle. Now say if I make updates and they are merged to PDS ldd-lro, you will now need to sync my updates back to your personal GitHub ldd-lro and back down to your local machines. Make changes and repeat....

A good way to test is to edit the README and see how it all works.

**Comment by paulgeissler** [comment]
Attached is the modified ingest file. Thanks!
[ldd-lro-1d00-pg.xml.txt](https://github.com/pds-data-dictionaries/ldd-lro/files/4602170/ldd-lro-1d00-pg.xml.txt)

**Comment by paulgeissler** [comment]
Thanks Susie! I have attached the modified ingest file, which produces schema and schematron files that are happy with multiple mission phases.  --Paul

Dr. Paul E. Geissler
Research Geologist
Center for Astrogeology
U.S. Geological Survey
2255 N. Gemini Drive
Flagstaff, AZ 86001 USA
(928) 556-7257 voice
(928) 556-7014 fax


________________________________________

**Comment by thareUSGS** [comment]
Added Paul's version. Let me know if you agree with the update to PDS 1D00 also.  You can see the files updated here: https://github.com/pds-data-dictionaries/ldd-lro/pull/7

**Comment by sslavney** [comment]
Got it. Yes, I agree with update to 1D00. Thanks, Paul and Trent and Jordan.
